# Generated by Django 4.2.6 on 2023-10-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pais_alter_tipoatuacao_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pais',
            old_name='descricao',
            new_name='nome',
        ),
    ]
