# Generated by Django 4.2.6 on 2023-10-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_membro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membro',
            old_name='data_nascimentp',
            new_name='data_nascimento',
        ),
    ]
