# Generated by Django 4.2.6 on 2023-10-18 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_data_nascimentp_membro_data_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('sinopse', models.TextField()),
                ('classificacao', models.IntegerField()),
                ('duracao', models.TimeField()),
                ('Produtora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produtora')),
            ],
        ),
    ]
